// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBflKwy3kjRHIh8Fa9i8VJ2c5-laq_yZSw',
    appId: '1:651355046383:web:16f085ece966277044361a',
    messagingSenderId: '651355046383',
    projectId: 'visual-central',
    authDomain: 'visual-central.firebaseapp.com',
    storageBucket: 'visual-central.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwr81YRI2L9Th86t23xAwSUwnMYtX3ffI',
    appId: '1:651355046383:android:4071731f3cdbe40644361a',
    messagingSenderId: '651355046383',
    projectId: 'visual-central',
    storageBucket: 'visual-central.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKXEoomgtqH8CFZw3zunIATQv0WkR88_c',
    appId: '1:651355046383:ios:889185f447651a3144361a',
    messagingSenderId: '651355046383',
    projectId: 'visual-central',
    storageBucket: 'visual-central.firebasestorage.app',
    iosBundleId: 'com.example.visualCentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKXEoomgtqH8CFZw3zunIATQv0WkR88_c',
    appId: '1:651355046383:ios:889185f447651a3144361a',
    messagingSenderId: '651355046383',
    projectId: 'visual-central',
    storageBucket: 'visual-central.firebasestorage.app',
    iosBundleId: 'com.example.visualCentral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBflKwy3kjRHIh8Fa9i8VJ2c5-laq_yZSw',
    appId: '1:651355046383:web:610a9c3f946850d744361a',
    messagingSenderId: '651355046383',
    projectId: 'visual-central',
    authDomain: 'visual-central.firebaseapp.com',
    storageBucket: 'visual-central.firebasestorage.app',
  );
}
